### ISSUE TITLE
error code: 1003

### ISSUE THREAD

**Issue by ashish-greycube** [frappe/storage_integration#1]
```
### App Versions
```
{
	"erpnext": "13.21.0",
	"frappe": "13.21.0",
	"storage_integration": "0.0.1"	
}
```
### Route
```
Form/Storage Integration Settings/Storage Integration Settings
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1213, in call
    return fn(*args, **newargs)
  File "apps/storage_integration/storage_integration/controller.py", line 153, in migrate_existing_files
    upload_to_s3(doc, None)
  File "apps/storage_integration/storage_integration/controller.py", line 126, in upload_to_s3
    conn.upload_file()
  File "apps/storage_integration/storage_integration/controller.py", line 30, in upload_file
    self.client.put_object(
  File "env/lib/python3.8/site-packages/minio/api.py", line 1761, in put_object
    raise exc
  File "env/lib/python3.8/site-packages/minio/api.py", line 1715, in put_object
    return self._put_object(
  File "env/lib/python3.8/site-packages/minio/api.py", line 1573, in _put_object
    response = self._execute(
  File "env/lib/python3.8/site-packages/minio/api.py", line 400, in _execute
    return self._url_open(
  File "env/lib/python3.8/site-packages/minio/api.py", line 309, in _url_open
    raise InvalidResponseError(
minio.error.InvalidResponseError: non-XML response from server; Response code: 403, Content-Type: text/plain; charset=UTF-8, Body: error code: 1003

```
### Request Data
```
{
	"type": "POST",
	"args": {},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/storage_integration.controller.migrate_existing_files"
}
```
### Response Data
```
{
	"exception": "minio.error.InvalidResponseError: non-XML response from server; Response code: 403, Content-Type: text/plain; charset=UTF-8, Body: error code: 1003"
}
```
```

**Comment by rutwikhdev** [comment]
Thanks for posting the issue.

Although I'm not able to replicate it. If you are trying to do this locally you will need to start a [minio gateway to s3](https://docs.min.io/docs/minio-gateway-for-s3.html). Then add the ip where the server is running and credentials to Storage Integration Settings Doctype.

Let me know if you need more information on setting this up.

Also you can add the steps you have tried to setup.

**Comment by RanaOsamaAsif** [comment]
@rutwikhdev I'm using this in production environment, what is supposed to be the IP in that case? Currently I'm using my server's URL i.e where frappe is hosted.

When I'm trying to upload a file the following error is thrown with status code 500.

`{
   "exception":"ValueError: path in endpoint is not allowed",
   "exc":"[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 69, in application\\n    response = frappe.api.handle()\\n  File \\\"apps/frappe/frappe/api.py\\\", line 55, in handle\\n    return frappe.handler.handle()\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 38, in handle\\n    data = execute_cmd(cmd)\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 76, in execute_cmd\\n    return frappe.call(method, **frappe.form_dict)\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 1462, in call\\n    return fn(*args, **newargs)\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 219, in upload_file\\n    ret.save(ignore_permissions=ignore_permissions)\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 312, in save\\n    return self._save(*args, **kwargs)\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 334, in _save\\n    return self.insert()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 284, in insert\\n    self.run_method(\\\"after_insert\\\")\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 943, in run_method\\n    out = Document.hook(fn)(self, *args, **kwargs)\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 1264, in composer\\n    return composed(self, method, *args, **kwargs)\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 1248, in runner\\n    add_to_return_value(self, f(self, method, *args, **kwargs))\\n  File \\\"apps/storage_integration/storage_integration/controller.py\\\", line 125, in upload_to_s3\\n    conn = MinioConnection(doc)\\n  File \\\"apps/storage_integration/storage_integration/controller.py\\\", line 13, in __init__\\n    self.client = Minio(\\n  File \\\"env/lib/python3.10/site-packages/minio/api.py\\\", line 130, in __init__\\n    self._base_url = BaseURL(\\n  File \\\"env/lib/python3.10/site-packages/minio/helpers.py\\\", line 399, in __init__\\n    raise ValueError(\\\"path in endpoint is not allowed\\\")\\nValueError: path in endpoint is not allowed\\n\"]"
}`
